name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 * * * *' # Her saat başı çalışır
  workflow_dispatch:     # İstersen manuel de tetikleyebilirsin

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v3

    - name: Python 3.11 yükle
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Gereksinimleri yükle
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp

    - name: update.py çalıştır
      run: python update.py
